# Tratamento de Exceções
## Definição

Ao executar o código Java, diferentes erros podem ocorrer: erros de codificação feitos pelo programador, erros devido a entrada errada ou outros imprevistos.

Quando ocorre um erro, o Java normalmente para e gera uma mensagem de erro. O termo técnico para isso é: Java lançará uma exceção (jogará um erro).
      
## Exceções comuns

### Divisão por zero

``` Java      
         public class Main {
	     public static void main(String[] args) {
		try{
			int i = 10;
			int j = 0;
			int x = i/j;
			System.out.println("Depois da Divisão");
		}catch (ArithmeticException e){
			System.out.println("Divisão por zero");
    }
```
          
### Conversão de tipos de dados inválidos

```	Java
   public class Main {
public static void main(String[] args) {
		try{
			Object o = new Object();
			String s = (String) o;
		} catch (Exception e) {
			System.out.println("Conversão Inválida"); 
		}
``` 

### Acessar uma posição inválida em um arranjo

``` Java
	     public class Main {
	     public static void main(String[] args) {
		try{
		     ArrayList<Integer> l = new ArrayList<>();
		     l.get(99)
		}catch (IndexOutOfBoundsException e){
		  System.out.println("Posição inválida no arranjo");
		  }
```
		  
### Acessar uma String nula

``` Java
          public class Main {
          public static void main(String[] args) {
		try{
			String s = null
			s.replace ("","");
		}catch (NullPointerException e){
			System.out.println("String nula");
```
	
## Bloco para capturar uma exceção

A instrução _try_ permite que você defina um bloco de código para ser testado quanto a erros enquanto está sendo executado.

A instrução _catch_ permite definir um bloco de código a ser executado, caso ocorra um erro no bloco _try_.

As palavras-chave _try_ e _catch_ vêm em pares:
          
## Bloco para capturar diferentes exceções


```java
try {
  //  Código que fará a tentativa
}
catch(Exception e) {
  //  Código que gerencia os erros
}

```

## Bloco finally
A instrução _finally_ permite executar código  após _try...catch_, independentemente do resultado:
	
```java
public class Main {
  public static void main(String[] args) {
    try {
      int[] myNumbers = {1, 2, 3};
      System.out.println(myNumbers[10]);
    } catch (Exception e) {
      System.out.println("Algo deu errado");
    } finally {
      System.out.println("Finalmente");
    }
  }
}
```

## Lançar uma exceção

A instrução _throw_ (lançar) permite que você crie um erro personalizado.

A instrução _throw_ é usada junto com um tipo de exceção. Existem muitos tipos de exceção disponíveis em Java:  _ArithmeticException, FileNotFoundException, ArrayIndexOutOfBoundsException, SecurityException,_ etc:

```java
public class Main {
  static void checkAge(int age) {
    if (age < 18) {
      throw new ArithmeticException("Access denied - You must be at least 18 years old.");
    }
    else {
      System.out.println("Access granted - You are old enough!");
    }
  }

  public static void main(String[] args) {
    checkAge(15); // Insere idade 15
  }
}
```

```
