# Tratamento de Exceções
## Definição
```java
As exceções ocorrem quando algo imprevisto acontece, elas podem ser provenientes de erros de lógica ou acesso a
recursos que talvez não estejam disponíveis.
```
## Exceções comuns
```java
O uso de exceções em um sistema é de extrema importância, pois ajuda a detectar e tratar possíveis erros que
possam acontecer. Entretanto, na linguagem Java existem dois tipos de exceções, que são:

Implícitas: Exceções que não precisam de tratamento e demonstram serem contornáveis. Esse tipo origina-se da
subclasse "Error" ou RunTimeException.

Explícitas: Exceções que precisam ser tratadas e que apresentam condições incontornáveis. Esse tipo origina
do modelo throw e necessita ser declarado pelos métodos. É originado da subclasse "Exception" ou "IOException".
```
### Divisão por zero
```java
public class App {
    public static void main(String[] args) {
        int a = 10;
        int b = 0;

        try{
            System.out.println(a / b);
        }
        catch (ArithmeticException e) {
            System.out.println();
            System.out.println("Não é possível dividir por zero");
            System.out.println();
        }
    }
}
```
### Conversão de tipos de dados inválidos
```java
public class App {
        public static void main(String[] args) {
                System.out.println();

                int a = 10;
                String text;

                try {
                        b = text = a;
                } catch (Exception e) {
                        System.out.println();
                        System.out.println("Não é possível converter tipos de dados diferentes");
                        System.out.println();
                }
        }
}
```
### Acessar uma posição inválida em um arranjo
### Acessar uma String nula
## Bloco para capturar uma exceção
```java
public class App {
        public static void main(String[] args) {
                System.out.println();
                System.out.println("Exceção básica matematica:");
                try{ 
                        int num1 = 100;
                        int num2 = 0;
                        int num3 = num1 / num2;
                }
                catch(ArithmeticException e) {
                        System.out.println();
                        System.out.println("Ops, a divisão não é possivel por conter um 0");
                        System.out.println();
                }
        }
}
```
## Bloco para capturar diferentes exceções
```java
public class App {
        public static void main(String[] args) {
                try {
                        int g = 10;
                        int h = 0;
                        int u = g / h;
                } catch (ArithmeticException e) {
                        System.out.println();
                        System.out.println("Impossivel realizar a divisão por 0");
                        System.out.println();
                } catch (Exception e) {
                        System.out.println();
                        System.out.println("Erro ocorre pois: " + e.getMessage()); //o getMessage trará a mensagem de erro da Exceção   
                        System.out.println();
                }
        }
} 
```
## Bloco finally
```java
O bloco finally é utilizado para garantir que um código seja executado após um try, mesmo que uma exceção tenha sido
gerada. Mesmo que tenha um return no try ou no catch, lembrando que o bloco finally sempre é executado.
```
```java
public class App {
        public static void main(String[] args) {
                System.out.println();

                try{
                        int f = 0;
                        int g = 0;
                        int h = f/g;
                }
                catch (Exception e) { 
                        System.out.println("Isso não é possível");
                }
                finally {
                        System.out.println("Caiu no finally");
                }
        }
}
```
## Lançar uma exceção
```java
public class App{
        public static void main(String[] args) {
                System.out.println("Exceção aritmética de divisão padrão");
                try{
                        int num1 = 8;
                        int num2 = 0;
                        if (num1 > 0) {
                                if (num2 == 0) {
                                        System.out.println();
                                        throw new ArithmeticException("Ops, divisão por zero...");
                                }
                        }
                }
                catch(Exception e) {
                        System.out.println();
                        System.out.println("Erro java: " + e.getMessage()); //Printará o erro da exceção
                        System.out.println();
                }
        }
}
```
